<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NonDbEntities\Configs\**" />
    <EmbeddedResource Remove="NonDbEntities\Configs\**" />
    <None Remove="NonDbEntities\Configs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.70" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="23.26.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProbashiShield.Shared\ProbashiShield.Shared.csproj" />
  </ItemGroup>

</Project>
